apiVersion: v1
kind: Namespace
metadata:
  name: ecocampus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecocampus-config
  namespace: ecocampus
data:
  NODE_ENV: "production"
  PORT_BACKEND: "5000"
  PORT_PYTHON: "5001"
  PORT_AI: "5002"
  MONGO_URI: "mongodb://mongodb-service.ecocampus.svc.cluster.local:27017/ecocampus"
  PYTHON_SERVICE_URL: "http://python-analyzer-service.ecocampus.svc.cluster.local:5001"
  EXPRESS_BACKEND_URL: "http://backend-service.ecocampus.svc.cluster.local:5000"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecocampus-secrets
  namespace: ecocampus
type: Opaque
stringData:
  JWT_SECRET: "ecocampus_k8s_super_secure_jwt_secret_2026"
  GEMINI_API_KEY: ""
  OPENAI_API_KEY: ""
